// <auto-generated />
namespace BankApp.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _004_DDL_Add_UserDeposit_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_004_DDL_Add_UserDeposit_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201603081150372_004_DDL_Add_UserDeposit_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
